langauge: python

python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=app tests/

after_success:
  - coveralls
  - codecov
