langauge: python

virtualenv:
  system_site_packages: true

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

before_install:
  - sudo -H pip install --upgrade pip
  - export SECRET_KEY=47479031
  
install:
  - pip install --user -r requirements.txt

after_success:
  - coveralls
  - codecov
