langauge: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install --user -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=app tests/

after_success:
  - coveralls

  cache: pip
