langauge: python

sudo: true

python:
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=app tests/ && coverage report

after_success:
  - coveralls

  cache: pip
