langauge: python

sudo: true

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo -H pip install --upgrade pip

install:
  - sudo pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=app tests/ && coverage report

after_success:
  - codecov
  - coveralls

  cache: pip
