langauge: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage --cover-package=app tests/ && coverage report

after_success:
  - codecov
  - coveralls

  cache: pip
